module PhoneNumbers.Countries exposing (countryAC, countryAD, countryAE, countryAF, countryAG, countryAI, countryAL, countryAM, countryAO, countryAR, countryAS, countryAT, countryAU, countryAW, countryAX, countryAZ, countryBA, countryBB, countryBD, countryBE, countryBF, countryBG, countryBH, countryBI, countryBJ, countryBL, countryBM, countryBN, countryBO, countryBQ, countryBR, countryBS, countryBT, countryBW, countryBY, countryBZ, countryCA, countryCC, countryCD, countryCF, countryCG, countryCH, countryCI, countryCK, countryCL, countryCM, countryCN, countryCO, countryCR, countryCU, countryCV, countryCW, countryCX, countryCY, countryCZ, countryDE, countryDJ, countryDK, countryDM, countryDO, countryDZ, countryEC, countryEE, countryEG, countryEH, countryER, countryES, countryET, countryFI, countryFJ, countryFK, countryFM, countryFO, countryFR, countryGA, countryGB, countryGD, countryGE, countryGF, countryGG, countryGH, countryGI, countryGL, countryGM, countryGN, countryGP, countryGQ, countryGR, countryGT, countryGU, countryGW, countryGY, countryHK, countryHN, countryHR, countryHT, countryHU, countryID, countryIE, countryIL, countryIM, countryIN, countryIO, countryIQ, countryIR, countryIS, countryIT, countryJE, countryJM, countryJO, countryJP, countryKE, countryKG, countryKH, countryKI, countryKM, countryKN, countryKP, countryKR, countryKW, countryKY, countryKZ, countryLA, countryLB, countryLC, countryLI, countryLK, countryLR, countryLS, countryLT, countryLU, countryLV, countryLY, countryMA, countryMC, countryMD, countryME, countryMF, countryMG, countryMH, countryMK, countryML, countryMM, countryMN, countryMO, countryMP, countryMQ, countryMR, countryMS, countryMT, countryMU, countryMV, countryMW, countryMX, countryMY, countryMZ, countryNA, countryNC, countryNE, countryNF, countryNG, countryNI, countryNL, countryNO, countryNP, countryNR, countryNU, countryNZ, countryOM, countryPA, countryPE, countryPF, countryPG, countryPH, countryPK, countryPL, countryPM, countryPR, countryPS, countryPT, countryPW, countryPY, countryQA, countryRE, countryRO, countryRS, countryRU, countryRW, countrySA, countrySB, countrySC, countrySD, countrySE, countrySG, countrySH, countrySI, countrySJ, countrySK, countrySL, countrySM, countrySN, countrySO, countrySR, countrySS, countryST, countrySV, countrySX, countrySY, countrySZ, countryTA, countryTC, countryTD, countryTG, countryTH, countryTJ, countryTK, countryTL, countryTM, countryTN, countryTO, countryTR, countryTT, countryTV, countryTW, countryTZ, countryUA, countryUG, countryUS, countryUY, countryUZ, countryVA, countryVC, countryVE, countryVG, countryVI, countryVN, countryVU, countryWF, countryWS, countryXK, countryYE, countryYT, countryZA, countryZM, countryZW)

{-| This file is auto generated. Do not edit this file directly.
-}

import PhoneNumbers


{-| -}
countryAC : PhoneNumbers.Territory
countryAC =
    { id = "AC"
    }


{-| -}
countryAD : PhoneNumbers.Territory
countryAD =
    { id = "AD"
    }


{-| -}
countryAE : PhoneNumbers.Territory
countryAE =
    { id = "AE"
    }


{-| -}
countryAF : PhoneNumbers.Territory
countryAF =
    { id = "AF"
    }


{-| -}
countryAG : PhoneNumbers.Territory
countryAG =
    { id = "AG"
    }


{-| -}
countryAI : PhoneNumbers.Territory
countryAI =
    { id = "AI"
    }


{-| -}
countryAL : PhoneNumbers.Territory
countryAL =
    { id = "AL"
    }


{-| -}
countryAM : PhoneNumbers.Territory
countryAM =
    { id = "AM"
    }


{-| -}
countryAO : PhoneNumbers.Territory
countryAO =
    { id = "AO"
    }


{-| -}
countryAR : PhoneNumbers.Territory
countryAR =
    { id = "AR"
    }


{-| -}
countryAS : PhoneNumbers.Territory
countryAS =
    { id = "AS"
    }


{-| -}
countryAT : PhoneNumbers.Territory
countryAT =
    { id = "AT"
    }


{-| -}
countryAU : PhoneNumbers.Territory
countryAU =
    { id = "AU"
    }


{-| -}
countryAW : PhoneNumbers.Territory
countryAW =
    { id = "AW"
    }


{-| -}
countryAX : PhoneNumbers.Territory
countryAX =
    { id = "AX"
    }


{-| -}
countryAZ : PhoneNumbers.Territory
countryAZ =
    { id = "AZ"
    }


{-| -}
countryBA : PhoneNumbers.Territory
countryBA =
    { id = "BA"
    }


{-| -}
countryBB : PhoneNumbers.Territory
countryBB =
    { id = "BB"
    }


{-| -}
countryBD : PhoneNumbers.Territory
countryBD =
    { id = "BD"
    }


{-| -}
countryBE : PhoneNumbers.Territory
countryBE =
    { id = "BE"
    }


{-| -}
countryBF : PhoneNumbers.Territory
countryBF =
    { id = "BF"
    }


{-| -}
countryBG : PhoneNumbers.Territory
countryBG =
    { id = "BG"
    }


{-| -}
countryBH : PhoneNumbers.Territory
countryBH =
    { id = "BH"
    }


{-| -}
countryBI : PhoneNumbers.Territory
countryBI =
    { id = "BI"
    }


{-| -}
countryBJ : PhoneNumbers.Territory
countryBJ =
    { id = "BJ"
    }


{-| -}
countryBL : PhoneNumbers.Territory
countryBL =
    { id = "BL"
    }


{-| -}
countryBM : PhoneNumbers.Territory
countryBM =
    { id = "BM"
    }


{-| -}
countryBN : PhoneNumbers.Territory
countryBN =
    { id = "BN"
    }


{-| -}
countryBO : PhoneNumbers.Territory
countryBO =
    { id = "BO"
    }


{-| -}
countryBQ : PhoneNumbers.Territory
countryBQ =
    { id = "BQ"
    }


{-| -}
countryBR : PhoneNumbers.Territory
countryBR =
    { id = "BR"
    }


{-| -}
countryBS : PhoneNumbers.Territory
countryBS =
    { id = "BS"
    }


{-| -}
countryBT : PhoneNumbers.Territory
countryBT =
    { id = "BT"
    }


{-| -}
countryBW : PhoneNumbers.Territory
countryBW =
    { id = "BW"
    }


{-| -}
countryBY : PhoneNumbers.Territory
countryBY =
    { id = "BY"
    }


{-| -}
countryBZ : PhoneNumbers.Territory
countryBZ =
    { id = "BZ"
    }


{-| -}
countryCA : PhoneNumbers.Territory
countryCA =
    { id = "CA"
    }


{-| -}
countryCC : PhoneNumbers.Territory
countryCC =
    { id = "CC"
    }


{-| -}
countryCD : PhoneNumbers.Territory
countryCD =
    { id = "CD"
    }


{-| -}
countryCF : PhoneNumbers.Territory
countryCF =
    { id = "CF"
    }


{-| -}
countryCG : PhoneNumbers.Territory
countryCG =
    { id = "CG"
    }


{-| -}
countryCH : PhoneNumbers.Territory
countryCH =
    { id = "CH"
    }


{-| -}
countryCI : PhoneNumbers.Territory
countryCI =
    { id = "CI"
    }


{-| -}
countryCK : PhoneNumbers.Territory
countryCK =
    { id = "CK"
    }


{-| -}
countryCL : PhoneNumbers.Territory
countryCL =
    { id = "CL"
    }


{-| -}
countryCM : PhoneNumbers.Territory
countryCM =
    { id = "CM"
    }


{-| -}
countryCN : PhoneNumbers.Territory
countryCN =
    { id = "CN"
    }


{-| -}
countryCO : PhoneNumbers.Territory
countryCO =
    { id = "CO"
    }


{-| -}
countryCR : PhoneNumbers.Territory
countryCR =
    { id = "CR"
    }


{-| -}
countryCU : PhoneNumbers.Territory
countryCU =
    { id = "CU"
    }


{-| -}
countryCV : PhoneNumbers.Territory
countryCV =
    { id = "CV"
    }


{-| -}
countryCW : PhoneNumbers.Territory
countryCW =
    { id = "CW"
    }


{-| -}
countryCX : PhoneNumbers.Territory
countryCX =
    { id = "CX"
    }


{-| -}
countryCY : PhoneNumbers.Territory
countryCY =
    { id = "CY"
    }


{-| -}
countryCZ : PhoneNumbers.Territory
countryCZ =
    { id = "CZ"
    }


{-| -}
countryDE : PhoneNumbers.Territory
countryDE =
    { id = "DE"
    }


{-| -}
countryDJ : PhoneNumbers.Territory
countryDJ =
    { id = "DJ"
    }


{-| -}
countryDK : PhoneNumbers.Territory
countryDK =
    { id = "DK"
    }


{-| -}
countryDM : PhoneNumbers.Territory
countryDM =
    { id = "DM"
    }


{-| -}
countryDO : PhoneNumbers.Territory
countryDO =
    { id = "DO"
    }


{-| -}
countryDZ : PhoneNumbers.Territory
countryDZ =
    { id = "DZ"
    }


{-| -}
countryEC : PhoneNumbers.Territory
countryEC =
    { id = "EC"
    }


{-| -}
countryEE : PhoneNumbers.Territory
countryEE =
    { id = "EE"
    }


{-| -}
countryEG : PhoneNumbers.Territory
countryEG =
    { id = "EG"
    }


{-| -}
countryEH : PhoneNumbers.Territory
countryEH =
    { id = "EH"
    }


{-| -}
countryER : PhoneNumbers.Territory
countryER =
    { id = "ER"
    }


{-| -}
countryES : PhoneNumbers.Territory
countryES =
    { id = "ES"
    }


{-| -}
countryET : PhoneNumbers.Territory
countryET =
    { id = "ET"
    }


{-| -}
countryFI : PhoneNumbers.Territory
countryFI =
    { id = "FI"
    }


{-| -}
countryFJ : PhoneNumbers.Territory
countryFJ =
    { id = "FJ"
    }


{-| -}
countryFK : PhoneNumbers.Territory
countryFK =
    { id = "FK"
    }


{-| -}
countryFM : PhoneNumbers.Territory
countryFM =
    { id = "FM"
    }


{-| -}
countryFO : PhoneNumbers.Territory
countryFO =
    { id = "FO"
    }


{-| -}
countryFR : PhoneNumbers.Territory
countryFR =
    { id = "FR"
    }


{-| -}
countryGA : PhoneNumbers.Territory
countryGA =
    { id = "GA"
    }


{-| -}
countryGB : PhoneNumbers.Territory
countryGB =
    { id = "GB"
    }


{-| -}
countryGD : PhoneNumbers.Territory
countryGD =
    { id = "GD"
    }


{-| -}
countryGE : PhoneNumbers.Territory
countryGE =
    { id = "GE"
    }


{-| -}
countryGF : PhoneNumbers.Territory
countryGF =
    { id = "GF"
    }


{-| -}
countryGG : PhoneNumbers.Territory
countryGG =
    { id = "GG"
    }


{-| -}
countryGH : PhoneNumbers.Territory
countryGH =
    { id = "GH"
    }


{-| -}
countryGI : PhoneNumbers.Territory
countryGI =
    { id = "GI"
    }


{-| -}
countryGL : PhoneNumbers.Territory
countryGL =
    { id = "GL"
    }


{-| -}
countryGM : PhoneNumbers.Territory
countryGM =
    { id = "GM"
    }


{-| -}
countryGN : PhoneNumbers.Territory
countryGN =
    { id = "GN"
    }


{-| -}
countryGP : PhoneNumbers.Territory
countryGP =
    { id = "GP"
    }


{-| -}
countryGQ : PhoneNumbers.Territory
countryGQ =
    { id = "GQ"
    }


{-| -}
countryGR : PhoneNumbers.Territory
countryGR =
    { id = "GR"
    }


{-| -}
countryGT : PhoneNumbers.Territory
countryGT =
    { id = "GT"
    }


{-| -}
countryGU : PhoneNumbers.Territory
countryGU =
    { id = "GU"
    }


{-| -}
countryGW : PhoneNumbers.Territory
countryGW =
    { id = "GW"
    }


{-| -}
countryGY : PhoneNumbers.Territory
countryGY =
    { id = "GY"
    }


{-| -}
countryHK : PhoneNumbers.Territory
countryHK =
    { id = "HK"
    }


{-| -}
countryHN : PhoneNumbers.Territory
countryHN =
    { id = "HN"
    }


{-| -}
countryHR : PhoneNumbers.Territory
countryHR =
    { id = "HR"
    }


{-| -}
countryHT : PhoneNumbers.Territory
countryHT =
    { id = "HT"
    }


{-| -}
countryHU : PhoneNumbers.Territory
countryHU =
    { id = "HU"
    }


{-| -}
countryID : PhoneNumbers.Territory
countryID =
    { id = "ID"
    }


{-| -}
countryIE : PhoneNumbers.Territory
countryIE =
    { id = "IE"
    }


{-| -}
countryIL : PhoneNumbers.Territory
countryIL =
    { id = "IL"
    }


{-| -}
countryIM : PhoneNumbers.Territory
countryIM =
    { id = "IM"
    }


{-| -}
countryIN : PhoneNumbers.Territory
countryIN =
    { id = "IN"
    }


{-| -}
countryIO : PhoneNumbers.Territory
countryIO =
    { id = "IO"
    }


{-| -}
countryIQ : PhoneNumbers.Territory
countryIQ =
    { id = "IQ"
    }


{-| -}
countryIR : PhoneNumbers.Territory
countryIR =
    { id = "IR"
    }


{-| -}
countryIS : PhoneNumbers.Territory
countryIS =
    { id = "IS"
    }


{-| -}
countryIT : PhoneNumbers.Territory
countryIT =
    { id = "IT"
    }


{-| -}
countryJE : PhoneNumbers.Territory
countryJE =
    { id = "JE"
    }


{-| -}
countryJM : PhoneNumbers.Territory
countryJM =
    { id = "JM"
    }


{-| -}
countryJO : PhoneNumbers.Territory
countryJO =
    { id = "JO"
    }


{-| -}
countryJP : PhoneNumbers.Territory
countryJP =
    { id = "JP"
    }


{-| -}
countryKE : PhoneNumbers.Territory
countryKE =
    { id = "KE"
    }


{-| -}
countryKG : PhoneNumbers.Territory
countryKG =
    { id = "KG"
    }


{-| -}
countryKH : PhoneNumbers.Territory
countryKH =
    { id = "KH"
    }


{-| -}
countryKI : PhoneNumbers.Territory
countryKI =
    { id = "KI"
    }


{-| -}
countryKM : PhoneNumbers.Territory
countryKM =
    { id = "KM"
    }


{-| -}
countryKN : PhoneNumbers.Territory
countryKN =
    { id = "KN"
    }


{-| -}
countryKP : PhoneNumbers.Territory
countryKP =
    { id = "KP"
    }


{-| -}
countryKR : PhoneNumbers.Territory
countryKR =
    { id = "KR"
    }


{-| -}
countryKW : PhoneNumbers.Territory
countryKW =
    { id = "KW"
    }


{-| -}
countryKY : PhoneNumbers.Territory
countryKY =
    { id = "KY"
    }


{-| -}
countryKZ : PhoneNumbers.Territory
countryKZ =
    { id = "KZ"
    }


{-| -}
countryLA : PhoneNumbers.Territory
countryLA =
    { id = "LA"
    }


{-| -}
countryLB : PhoneNumbers.Territory
countryLB =
    { id = "LB"
    }


{-| -}
countryLC : PhoneNumbers.Territory
countryLC =
    { id = "LC"
    }


{-| -}
countryLI : PhoneNumbers.Territory
countryLI =
    { id = "LI"
    }


{-| -}
countryLK : PhoneNumbers.Territory
countryLK =
    { id = "LK"
    }


{-| -}
countryLR : PhoneNumbers.Territory
countryLR =
    { id = "LR"
    }


{-| -}
countryLS : PhoneNumbers.Territory
countryLS =
    { id = "LS"
    }


{-| -}
countryLT : PhoneNumbers.Territory
countryLT =
    { id = "LT"
    }


{-| -}
countryLU : PhoneNumbers.Territory
countryLU =
    { id = "LU"
    }


{-| -}
countryLV : PhoneNumbers.Territory
countryLV =
    { id = "LV"
    }


{-| -}
countryLY : PhoneNumbers.Territory
countryLY =
    { id = "LY"
    }


{-| -}
countryMA : PhoneNumbers.Territory
countryMA =
    { id = "MA"
    }


{-| -}
countryMC : PhoneNumbers.Territory
countryMC =
    { id = "MC"
    }


{-| -}
countryMD : PhoneNumbers.Territory
countryMD =
    { id = "MD"
    }


{-| -}
countryME : PhoneNumbers.Territory
countryME =
    { id = "ME"
    }


{-| -}
countryMF : PhoneNumbers.Territory
countryMF =
    { id = "MF"
    }


{-| -}
countryMG : PhoneNumbers.Territory
countryMG =
    { id = "MG"
    }


{-| -}
countryMH : PhoneNumbers.Territory
countryMH =
    { id = "MH"
    }


{-| -}
countryMK : PhoneNumbers.Territory
countryMK =
    { id = "MK"
    }


{-| -}
countryML : PhoneNumbers.Territory
countryML =
    { id = "ML"
    }


{-| -}
countryMM : PhoneNumbers.Territory
countryMM =
    { id = "MM"
    }


{-| -}
countryMN : PhoneNumbers.Territory
countryMN =
    { id = "MN"
    }


{-| -}
countryMO : PhoneNumbers.Territory
countryMO =
    { id = "MO"
    }


{-| -}
countryMP : PhoneNumbers.Territory
countryMP =
    { id = "MP"
    }


{-| -}
countryMQ : PhoneNumbers.Territory
countryMQ =
    { id = "MQ"
    }


{-| -}
countryMR : PhoneNumbers.Territory
countryMR =
    { id = "MR"
    }


{-| -}
countryMS : PhoneNumbers.Territory
countryMS =
    { id = "MS"
    }


{-| -}
countryMT : PhoneNumbers.Territory
countryMT =
    { id = "MT"
    }


{-| -}
countryMU : PhoneNumbers.Territory
countryMU =
    { id = "MU"
    }


{-| -}
countryMV : PhoneNumbers.Territory
countryMV =
    { id = "MV"
    }


{-| -}
countryMW : PhoneNumbers.Territory
countryMW =
    { id = "MW"
    }


{-| -}
countryMX : PhoneNumbers.Territory
countryMX =
    { id = "MX"
    }


{-| -}
countryMY : PhoneNumbers.Territory
countryMY =
    { id = "MY"
    }


{-| -}
countryMZ : PhoneNumbers.Territory
countryMZ =
    { id = "MZ"
    }


{-| -}
countryNA : PhoneNumbers.Territory
countryNA =
    { id = "NA"
    }


{-| -}
countryNC : PhoneNumbers.Territory
countryNC =
    { id = "NC"
    }


{-| -}
countryNE : PhoneNumbers.Territory
countryNE =
    { id = "NE"
    }


{-| -}
countryNF : PhoneNumbers.Territory
countryNF =
    { id = "NF"
    }


{-| -}
countryNG : PhoneNumbers.Territory
countryNG =
    { id = "NG"
    }


{-| -}
countryNI : PhoneNumbers.Territory
countryNI =
    { id = "NI"
    }


{-| -}
countryNL : PhoneNumbers.Territory
countryNL =
    { id = "NL"
    }


{-| -}
countryNO : PhoneNumbers.Territory
countryNO =
    { id = "NO"
    }


{-| -}
countryNP : PhoneNumbers.Territory
countryNP =
    { id = "NP"
    }


{-| -}
countryNR : PhoneNumbers.Territory
countryNR =
    { id = "NR"
    }


{-| -}
countryNU : PhoneNumbers.Territory
countryNU =
    { id = "NU"
    }


{-| -}
countryNZ : PhoneNumbers.Territory
countryNZ =
    { id = "NZ"
    }


{-| -}
countryOM : PhoneNumbers.Territory
countryOM =
    { id = "OM"
    }


{-| -}
countryPA : PhoneNumbers.Territory
countryPA =
    { id = "PA"
    }


{-| -}
countryPE : PhoneNumbers.Territory
countryPE =
    { id = "PE"
    }


{-| -}
countryPF : PhoneNumbers.Territory
countryPF =
    { id = "PF"
    }


{-| -}
countryPG : PhoneNumbers.Territory
countryPG =
    { id = "PG"
    }


{-| -}
countryPH : PhoneNumbers.Territory
countryPH =
    { id = "PH"
    }


{-| -}
countryPK : PhoneNumbers.Territory
countryPK =
    { id = "PK"
    }


{-| -}
countryPL : PhoneNumbers.Territory
countryPL =
    { id = "PL"
    }


{-| -}
countryPM : PhoneNumbers.Territory
countryPM =
    { id = "PM"
    }


{-| -}
countryPR : PhoneNumbers.Territory
countryPR =
    { id = "PR"
    }


{-| -}
countryPS : PhoneNumbers.Territory
countryPS =
    { id = "PS"
    }


{-| -}
countryPT : PhoneNumbers.Territory
countryPT =
    { id = "PT"
    }


{-| -}
countryPW : PhoneNumbers.Territory
countryPW =
    { id = "PW"
    }


{-| -}
countryPY : PhoneNumbers.Territory
countryPY =
    { id = "PY"
    }


{-| -}
countryQA : PhoneNumbers.Territory
countryQA =
    { id = "QA"
    }


{-| -}
countryRE : PhoneNumbers.Territory
countryRE =
    { id = "RE"
    }


{-| -}
countryRO : PhoneNumbers.Territory
countryRO =
    { id = "RO"
    }


{-| -}
countryRS : PhoneNumbers.Territory
countryRS =
    { id = "RS"
    }


{-| -}
countryRU : PhoneNumbers.Territory
countryRU =
    { id = "RU"
    }


{-| -}
countryRW : PhoneNumbers.Territory
countryRW =
    { id = "RW"
    }


{-| -}
countrySA : PhoneNumbers.Territory
countrySA =
    { id = "SA"
    }


{-| -}
countrySB : PhoneNumbers.Territory
countrySB =
    { id = "SB"
    }


{-| -}
countrySC : PhoneNumbers.Territory
countrySC =
    { id = "SC"
    }


{-| -}
countrySD : PhoneNumbers.Territory
countrySD =
    { id = "SD"
    }


{-| -}
countrySE : PhoneNumbers.Territory
countrySE =
    { id = "SE"
    }


{-| -}
countrySG : PhoneNumbers.Territory
countrySG =
    { id = "SG"
    }


{-| -}
countrySH : PhoneNumbers.Territory
countrySH =
    { id = "SH"
    }


{-| -}
countrySI : PhoneNumbers.Territory
countrySI =
    { id = "SI"
    }


{-| -}
countrySJ : PhoneNumbers.Territory
countrySJ =
    { id = "SJ"
    }


{-| -}
countrySK : PhoneNumbers.Territory
countrySK =
    { id = "SK"
    }


{-| -}
countrySL : PhoneNumbers.Territory
countrySL =
    { id = "SL"
    }


{-| -}
countrySM : PhoneNumbers.Territory
countrySM =
    { id = "SM"
    }


{-| -}
countrySN : PhoneNumbers.Territory
countrySN =
    { id = "SN"
    }


{-| -}
countrySO : PhoneNumbers.Territory
countrySO =
    { id = "SO"
    }


{-| -}
countrySR : PhoneNumbers.Territory
countrySR =
    { id = "SR"
    }


{-| -}
countrySS : PhoneNumbers.Territory
countrySS =
    { id = "SS"
    }


{-| -}
countryST : PhoneNumbers.Territory
countryST =
    { id = "ST"
    }


{-| -}
countrySV : PhoneNumbers.Territory
countrySV =
    { id = "SV"
    }


{-| -}
countrySX : PhoneNumbers.Territory
countrySX =
    { id = "SX"
    }


{-| -}
countrySY : PhoneNumbers.Territory
countrySY =
    { id = "SY"
    }


{-| -}
countrySZ : PhoneNumbers.Territory
countrySZ =
    { id = "SZ"
    }


{-| -}
countryTA : PhoneNumbers.Territory
countryTA =
    { id = "TA"
    }


{-| -}
countryTC : PhoneNumbers.Territory
countryTC =
    { id = "TC"
    }


{-| -}
countryTD : PhoneNumbers.Territory
countryTD =
    { id = "TD"
    }


{-| -}
countryTG : PhoneNumbers.Territory
countryTG =
    { id = "TG"
    }


{-| -}
countryTH : PhoneNumbers.Territory
countryTH =
    { id = "TH"
    }


{-| -}
countryTJ : PhoneNumbers.Territory
countryTJ =
    { id = "TJ"
    }


{-| -}
countryTK : PhoneNumbers.Territory
countryTK =
    { id = "TK"
    }


{-| -}
countryTL : PhoneNumbers.Territory
countryTL =
    { id = "TL"
    }


{-| -}
countryTM : PhoneNumbers.Territory
countryTM =
    { id = "TM"
    }


{-| -}
countryTN : PhoneNumbers.Territory
countryTN =
    { id = "TN"
    }


{-| -}
countryTO : PhoneNumbers.Territory
countryTO =
    { id = "TO"
    }


{-| -}
countryTR : PhoneNumbers.Territory
countryTR =
    { id = "TR"
    }


{-| -}
countryTT : PhoneNumbers.Territory
countryTT =
    { id = "TT"
    }


{-| -}
countryTV : PhoneNumbers.Territory
countryTV =
    { id = "TV"
    }


{-| -}
countryTW : PhoneNumbers.Territory
countryTW =
    { id = "TW"
    }


{-| -}
countryTZ : PhoneNumbers.Territory
countryTZ =
    { id = "TZ"
    }


{-| -}
countryUA : PhoneNumbers.Territory
countryUA =
    { id = "UA"
    }


{-| -}
countryUG : PhoneNumbers.Territory
countryUG =
    { id = "UG"
    }


{-| -}
countryUS : PhoneNumbers.Territory
countryUS =
    { id = "US"
    }


{-| -}
countryUY : PhoneNumbers.Territory
countryUY =
    { id = "UY"
    }


{-| -}
countryUZ : PhoneNumbers.Territory
countryUZ =
    { id = "UZ"
    }


{-| -}
countryVA : PhoneNumbers.Territory
countryVA =
    { id = "VA"
    }


{-| -}
countryVC : PhoneNumbers.Territory
countryVC =
    { id = "VC"
    }


{-| -}
countryVE : PhoneNumbers.Territory
countryVE =
    { id = "VE"
    }


{-| -}
countryVG : PhoneNumbers.Territory
countryVG =
    { id = "VG"
    }


{-| -}
countryVI : PhoneNumbers.Territory
countryVI =
    { id = "VI"
    }


{-| -}
countryVN : PhoneNumbers.Territory
countryVN =
    { id = "VN"
    }


{-| -}
countryVU : PhoneNumbers.Territory
countryVU =
    { id = "VU"
    }


{-| -}
countryWF : PhoneNumbers.Territory
countryWF =
    { id = "WF"
    }


{-| -}
countryWS : PhoneNumbers.Territory
countryWS =
    { id = "WS"
    }


{-| -}
countryXK : PhoneNumbers.Territory
countryXK =
    { id = "XK"
    }


{-| -}
countryYE : PhoneNumbers.Territory
countryYE =
    { id = "YE"
    }


{-| -}
countryYT : PhoneNumbers.Territory
countryYT =
    { id = "YT"
    }


{-| -}
countryZA : PhoneNumbers.Territory
countryZA =
    { id = "ZA"
    }


{-| -}
countryZM : PhoneNumbers.Territory
countryZM =
    { id = "ZM"
    }


{-| -}
countryZW : PhoneNumbers.Territory
countryZW =
    { id = "ZW"
    }
