module PhoneNumbers.Countries exposing (countryAC, countryAD, countryAE, countryAF, countryAG, countryAI, countryAL, countryAM, countryAO, countryAR, countryAS, countryAT, countryAU, countryAW, countryAX, countryAZ, countryBA, countryBB, countryBD, countryBE, countryBF, countryBG, countryBH, countryBI, countryBJ, countryBL, countryBM, countryBN, countryBO, countryBQ, countryBR, countryBS, countryBT, countryBW, countryBY, countryBZ, countryCA, countryCC, countryCD, countryCF, countryCG, countryCH, countryCI, countryCK, countryCL, countryCM, countryCN, countryCO, countryCR, countryCU, countryCV, countryCW, countryCX, countryCY, countryCZ, countryDE, countryDJ, countryDK, countryDM, countryDO, countryDZ, countryEC, countryEE, countryEG, countryEH, countryER, countryES, countryET, countryFI, countryFJ, countryFK, countryFM, countryFO, countryFR, countryGA, countryGB, countryGD, countryGE, countryGF, countryGG, countryGH, countryGI, countryGL, countryGM, countryGN, countryGP, countryGQ, countryGR, countryGT, countryGU, countryGW, countryGY, countryHK, countryHN, countryHR, countryHT, countryHU, countryID, countryIE, countryIL, countryIM, countryIN, countryIO, countryIQ, countryIR, countryIS, countryIT, countryJE, countryJM, countryJO, countryJP, countryKE, countryKG, countryKH, countryKI, countryKM, countryKN, countryKP, countryKR, countryKW, countryKY, countryKZ, countryLA, countryLB, countryLC, countryLI, countryLK, countryLR, countryLS, countryLT, countryLU, countryLV, countryLY, countryMA, countryMC, countryMD, countryME, countryMF, countryMG, countryMH, countryMK, countryML, countryMM, countryMN, countryMO, countryMP, countryMQ, countryMR, countryMS, countryMT, countryMU, countryMV, countryMW, countryMX, countryMY, countryMZ, countryNA, countryNC, countryNE, countryNF, countryNG, countryNI, countryNL, countryNO, countryNP, countryNR, countryNU, countryNZ, countryOM, countryPA, countryPE, countryPF, countryPG, countryPH, countryPK, countryPL, countryPM, countryPR, countryPS, countryPT, countryPW, countryPY, countryQA, countryRE, countryRO, countryRS, countryRU, countryRW, countrySA, countrySB, countrySC, countrySD, countrySE, countrySG, countrySH, countrySI, countrySJ, countrySK, countrySL, countrySM, countrySN, countrySO, countrySR, countrySS, countryST, countrySV, countrySX, countrySY, countrySZ, countryTA, countryTC, countryTD, countryTG, countryTH, countryTJ, countryTK, countryTL, countryTM, countryTN, countryTO, countryTR, countryTT, countryTV, countryTW, countryTZ, countryUA, countryUG, countryUS, countryUY, countryUZ, countryVA, countryVC, countryVE, countryVG, countryVI, countryVN, countryVU, countryWF, countryWS, countryXK, countryYE, countryYT, countryZA, countryZM, countryZW)

{-| This file is auto generated. Do not edit this file directly.
-}

import PhoneNumbers


{-| -}
countryAC : PhoneNumbers.Territory
countryAC =
    { id = "AC"
    , countryCode = Just 247
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryAD : PhoneNumbers.Territory
countryAD =
    { id = "AD"
    , countryCode = Just 376
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryAE : PhoneNumbers.Territory
countryAE =
    { id = "AE"
    , countryCode = Just 971
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryAF : PhoneNumbers.Territory
countryAF =
    { id = "AF"
    , countryCode = Just 93
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryAG : PhoneNumbers.Territory
countryAG =
    { id = "AG"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryAI : PhoneNumbers.Territory
countryAI =
    { id = "AI"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryAL : PhoneNumbers.Territory
countryAL =
    { id = "AL"
    , countryCode = Just 355
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryAM : PhoneNumbers.Territory
countryAM =
    { id = "AM"
    , countryCode = Just 374
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryAO : PhoneNumbers.Territory
countryAO =
    { id = "AO"
    , countryCode = Just 244
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryAR : PhoneNumbers.Territory
countryAR =
    { id = "AR"
    , countryCode = Just 54
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryAS : PhoneNumbers.Territory
countryAS =
    { id = "AS"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryAT : PhoneNumbers.Territory
countryAT =
    { id = "AT"
    , countryCode = Just 43
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryAU : PhoneNumbers.Territory
countryAU =
    { id = "AU"
    , countryCode = Just 61
    , internationalPrefix = Just "001[14-689]|14(?:1[14]|34|4[17]|[56]6|7[47]|88)0011"
    , nationalPrefix = Just "0"
    }


{-| -}
countryAW : PhoneNumbers.Territory
countryAW =
    { id = "AW"
    , countryCode = Just 297
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryAX : PhoneNumbers.Territory
countryAX =
    { id = "AX"
    , countryCode = Just 358
    , internationalPrefix = Just "00|99(?:[01469]|5(?:[14]1|3[23]|5[59]|77|88|9[09]))"
    , nationalPrefix = Just "0"
    }


{-| -}
countryAZ : PhoneNumbers.Territory
countryAZ =
    { id = "AZ"
    , countryCode = Just 994
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryBA : PhoneNumbers.Territory
countryBA =
    { id = "BA"
    , countryCode = Just 387
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryBB : PhoneNumbers.Territory
countryBB =
    { id = "BB"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryBD : PhoneNumbers.Territory
countryBD =
    { id = "BD"
    , countryCode = Just 880
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryBE : PhoneNumbers.Territory
countryBE =
    { id = "BE"
    , countryCode = Just 32
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryBF : PhoneNumbers.Territory
countryBF =
    { id = "BF"
    , countryCode = Just 226
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryBG : PhoneNumbers.Territory
countryBG =
    { id = "BG"
    , countryCode = Just 359
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryBH : PhoneNumbers.Territory
countryBH =
    { id = "BH"
    , countryCode = Just 973
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryBI : PhoneNumbers.Territory
countryBI =
    { id = "BI"
    , countryCode = Just 257
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryBJ : PhoneNumbers.Territory
countryBJ =
    { id = "BJ"
    , countryCode = Just 229
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryBL : PhoneNumbers.Territory
countryBL =
    { id = "BL"
    , countryCode = Just 590
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryBM : PhoneNumbers.Territory
countryBM =
    { id = "BM"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryBN : PhoneNumbers.Territory
countryBN =
    { id = "BN"
    , countryCode = Just 673
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryBO : PhoneNumbers.Territory
countryBO =
    { id = "BO"
    , countryCode = Just 591
    , internationalPrefix = Just "00(?:1\\d)?"
    , nationalPrefix = Just "0"
    }


{-| -}
countryBQ : PhoneNumbers.Territory
countryBQ =
    { id = "BQ"
    , countryCode = Just 599
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryBR : PhoneNumbers.Territory
countryBR =
    { id = "BR"
    , countryCode = Just 55
    , internationalPrefix = Just "00(?:1[245]|2[1-35]|31|4[13]|[56]5|99)"
    , nationalPrefix = Just "0"
    }


{-| -}
countryBS : PhoneNumbers.Territory
countryBS =
    { id = "BS"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryBT : PhoneNumbers.Territory
countryBT =
    { id = "BT"
    , countryCode = Just 975
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryBW : PhoneNumbers.Territory
countryBW =
    { id = "BW"
    , countryCode = Just 267
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryBY : PhoneNumbers.Territory
countryBY =
    { id = "BY"
    , countryCode = Just 375
    , internationalPrefix = Just "810"
    , nationalPrefix = Just "8"
    }


{-| -}
countryBZ : PhoneNumbers.Territory
countryBZ =
    { id = "BZ"
    , countryCode = Just 501
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryCA : PhoneNumbers.Territory
countryCA =
    { id = "CA"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryCC : PhoneNumbers.Territory
countryCC =
    { id = "CC"
    , countryCode = Just 61
    , internationalPrefix = Just "001[14-689]|14(?:1[14]|34|4[17]|[56]6|7[47]|88)0011"
    , nationalPrefix = Just "0"
    }


{-| -}
countryCD : PhoneNumbers.Territory
countryCD =
    { id = "CD"
    , countryCode = Just 243
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryCF : PhoneNumbers.Territory
countryCF =
    { id = "CF"
    , countryCode = Just 236
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryCG : PhoneNumbers.Territory
countryCG =
    { id = "CG"
    , countryCode = Just 242
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryCH : PhoneNumbers.Territory
countryCH =
    { id = "CH"
    , countryCode = Just 41
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryCI : PhoneNumbers.Territory
countryCI =
    { id = "CI"
    , countryCode = Just 225
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryCK : PhoneNumbers.Territory
countryCK =
    { id = "CK"
    , countryCode = Just 682
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryCL : PhoneNumbers.Territory
countryCL =
    { id = "CL"
    , countryCode = Just 56
    , internationalPrefix = Just "(?:0|1(?:1[0-69]|2[0-57]|5[13-58]|69|7[0167]|8[018]))0"
    , nationalPrefix = Nothing
    }


{-| -}
countryCM : PhoneNumbers.Territory
countryCM =
    { id = "CM"
    , countryCode = Just 237
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryCN : PhoneNumbers.Territory
countryCN =
    { id = "CN"
    , countryCode = Just 86
    , internationalPrefix = Just "(?:1(?:[12]\\d{3}|79\\d{2}|9[0-7]\\d{2}))?00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryCO : PhoneNumbers.Territory
countryCO =
    { id = "CO"
    , countryCode = Just 57
    , internationalPrefix = Just "00(?:4(?:[14]4|56)|[579])"
    , nationalPrefix = Just "0"
    }


{-| -}
countryCR : PhoneNumbers.Territory
countryCR =
    { id = "CR"
    , countryCode = Just 506
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryCU : PhoneNumbers.Territory
countryCU =
    { id = "CU"
    , countryCode = Just 53
    , internationalPrefix = Just "119"
    , nationalPrefix = Just "0"
    }


{-| -}
countryCV : PhoneNumbers.Territory
countryCV =
    { id = "CV"
    , countryCode = Just 238
    , internationalPrefix = Just "0"
    , nationalPrefix = Nothing
    }


{-| -}
countryCW : PhoneNumbers.Territory
countryCW =
    { id = "CW"
    , countryCode = Just 599
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryCX : PhoneNumbers.Territory
countryCX =
    { id = "CX"
    , countryCode = Just 61
    , internationalPrefix = Just "001[14-689]|14(?:1[14]|34|4[17]|[56]6|7[47]|88)0011"
    , nationalPrefix = Just "0"
    }


{-| -}
countryCY : PhoneNumbers.Territory
countryCY =
    { id = "CY"
    , countryCode = Just 357
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryCZ : PhoneNumbers.Territory
countryCZ =
    { id = "CZ"
    , countryCode = Just 420
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryDE : PhoneNumbers.Territory
countryDE =
    { id = "DE"
    , countryCode = Just 49
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryDJ : PhoneNumbers.Territory
countryDJ =
    { id = "DJ"
    , countryCode = Just 253
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryDK : PhoneNumbers.Territory
countryDK =
    { id = "DK"
    , countryCode = Just 45
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryDM : PhoneNumbers.Territory
countryDM =
    { id = "DM"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryDO : PhoneNumbers.Territory
countryDO =
    { id = "DO"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryDZ : PhoneNumbers.Territory
countryDZ =
    { id = "DZ"
    , countryCode = Just 213
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryEC : PhoneNumbers.Territory
countryEC =
    { id = "EC"
    , countryCode = Just 593
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryEE : PhoneNumbers.Territory
countryEE =
    { id = "EE"
    , countryCode = Just 372
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryEG : PhoneNumbers.Territory
countryEG =
    { id = "EG"
    , countryCode = Just 20
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryEH : PhoneNumbers.Territory
countryEH =
    { id = "EH"
    , countryCode = Just 212
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryER : PhoneNumbers.Territory
countryER =
    { id = "ER"
    , countryCode = Just 291
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryES : PhoneNumbers.Territory
countryES =
    { id = "ES"
    , countryCode = Just 34
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryET : PhoneNumbers.Territory
countryET =
    { id = "ET"
    , countryCode = Just 251
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryFI : PhoneNumbers.Territory
countryFI =
    { id = "FI"
    , countryCode = Just 358
    , internationalPrefix = Just "00|99(?:[01469]|5(?:[14]1|3[23]|5[59]|77|88|9[09]))"
    , nationalPrefix = Just "0"
    }


{-| -}
countryFJ : PhoneNumbers.Territory
countryFJ =
    { id = "FJ"
    , countryCode = Just 679
    , internationalPrefix = Just "0(?:0|52)"
    , nationalPrefix = Nothing
    }


{-| -}
countryFK : PhoneNumbers.Territory
countryFK =
    { id = "FK"
    , countryCode = Just 500
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryFM : PhoneNumbers.Territory
countryFM =
    { id = "FM"
    , countryCode = Just 691
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryFO : PhoneNumbers.Territory
countryFO =
    { id = "FO"
    , countryCode = Just 298
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryFR : PhoneNumbers.Territory
countryFR =
    { id = "FR"
    , countryCode = Just 33
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryGA : PhoneNumbers.Territory
countryGA =
    { id = "GA"
    , countryCode = Just 241
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryGB : PhoneNumbers.Territory
countryGB =
    { id = "GB"
    , countryCode = Just 44
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryGD : PhoneNumbers.Territory
countryGD =
    { id = "GD"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryGE : PhoneNumbers.Territory
countryGE =
    { id = "GE"
    , countryCode = Just 995
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryGF : PhoneNumbers.Territory
countryGF =
    { id = "GF"
    , countryCode = Just 594
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryGG : PhoneNumbers.Territory
countryGG =
    { id = "GG"
    , countryCode = Just 44
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryGH : PhoneNumbers.Territory
countryGH =
    { id = "GH"
    , countryCode = Just 233
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryGI : PhoneNumbers.Territory
countryGI =
    { id = "GI"
    , countryCode = Just 350
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryGL : PhoneNumbers.Territory
countryGL =
    { id = "GL"
    , countryCode = Just 299
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryGM : PhoneNumbers.Territory
countryGM =
    { id = "GM"
    , countryCode = Just 220
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryGN : PhoneNumbers.Territory
countryGN =
    { id = "GN"
    , countryCode = Just 224
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryGP : PhoneNumbers.Territory
countryGP =
    { id = "GP"
    , countryCode = Just 590
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryGQ : PhoneNumbers.Territory
countryGQ =
    { id = "GQ"
    , countryCode = Just 240
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryGR : PhoneNumbers.Territory
countryGR =
    { id = "GR"
    , countryCode = Just 30
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryGT : PhoneNumbers.Territory
countryGT =
    { id = "GT"
    , countryCode = Just 502
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryGU : PhoneNumbers.Territory
countryGU =
    { id = "GU"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryGW : PhoneNumbers.Territory
countryGW =
    { id = "GW"
    , countryCode = Just 245
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryGY : PhoneNumbers.Territory
countryGY =
    { id = "GY"
    , countryCode = Just 592
    , internationalPrefix = Just "001"
    , nationalPrefix = Nothing
    }


{-| -}
countryHK : PhoneNumbers.Territory
countryHK =
    { id = "HK"
    , countryCode = Just 852
    , internationalPrefix = Just "00(?:30|5[09]|[126-9]?)"
    , nationalPrefix = Nothing
    }


{-| -}
countryHN : PhoneNumbers.Territory
countryHN =
    { id = "HN"
    , countryCode = Just 504
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryHR : PhoneNumbers.Territory
countryHR =
    { id = "HR"
    , countryCode = Just 385
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryHT : PhoneNumbers.Territory
countryHT =
    { id = "HT"
    , countryCode = Just 509
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryHU : PhoneNumbers.Territory
countryHU =
    { id = "HU"
    , countryCode = Just 36
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "06"
    }


{-| -}
countryID : PhoneNumbers.Territory
countryID =
    { id = "ID"
    , countryCode = Just 62
    , internationalPrefix = Just "0(?:0[17-9]|10(?:00|1[67]))"
    , nationalPrefix = Just "0"
    }


{-| -}
countryIE : PhoneNumbers.Territory
countryIE =
    { id = "IE"
    , countryCode = Just 353
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryIL : PhoneNumbers.Territory
countryIL =
    { id = "IL"
    , countryCode = Just 972
    , internationalPrefix = Just "0(?:0|1[2-9])"
    , nationalPrefix = Just "0"
    }


{-| -}
countryIM : PhoneNumbers.Territory
countryIM =
    { id = "IM"
    , countryCode = Just 44
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryIN : PhoneNumbers.Territory
countryIN =
    { id = "IN"
    , countryCode = Just 91
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryIO : PhoneNumbers.Territory
countryIO =
    { id = "IO"
    , countryCode = Just 246
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryIQ : PhoneNumbers.Territory
countryIQ =
    { id = "IQ"
    , countryCode = Just 964
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryIR : PhoneNumbers.Territory
countryIR =
    { id = "IR"
    , countryCode = Just 98
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryIS : PhoneNumbers.Territory
countryIS =
    { id = "IS"
    , countryCode = Just 354
    , internationalPrefix = Just "00|1(?:0(?:01|[12]0)|100)"
    , nationalPrefix = Nothing
    }


{-| -}
countryIT : PhoneNumbers.Territory
countryIT =
    { id = "IT"
    , countryCode = Just 39
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryJE : PhoneNumbers.Territory
countryJE =
    { id = "JE"
    , countryCode = Just 44
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryJM : PhoneNumbers.Territory
countryJM =
    { id = "JM"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryJO : PhoneNumbers.Territory
countryJO =
    { id = "JO"
    , countryCode = Just 962
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryJP : PhoneNumbers.Territory
countryJP =
    { id = "JP"
    , countryCode = Just 81
    , internationalPrefix = Just "010"
    , nationalPrefix = Just "0"
    }


{-| -}
countryKE : PhoneNumbers.Territory
countryKE =
    { id = "KE"
    , countryCode = Just 254
    , internationalPrefix = Just "000"
    , nationalPrefix = Just "0"
    }


{-| -}
countryKG : PhoneNumbers.Territory
countryKG =
    { id = "KG"
    , countryCode = Just 996
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryKH : PhoneNumbers.Territory
countryKH =
    { id = "KH"
    , countryCode = Just 855
    , internationalPrefix = Just "00[14-9]"
    , nationalPrefix = Just "0"
    }


{-| -}
countryKI : PhoneNumbers.Territory
countryKI =
    { id = "KI"
    , countryCode = Just 686
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryKM : PhoneNumbers.Territory
countryKM =
    { id = "KM"
    , countryCode = Just 269
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryKN : PhoneNumbers.Territory
countryKN =
    { id = "KN"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryKP : PhoneNumbers.Territory
countryKP =
    { id = "KP"
    , countryCode = Just 850
    , internationalPrefix = Just "00|99"
    , nationalPrefix = Just "0"
    }


{-| -}
countryKR : PhoneNumbers.Territory
countryKR =
    { id = "KR"
    , countryCode = Just 82
    , internationalPrefix = Just "00(?:[125689]|3(?:[46]5|91)|7(?:00|27|3|55|6[126]))"
    , nationalPrefix = Just "0"
    }


{-| -}
countryKW : PhoneNumbers.Territory
countryKW =
    { id = "KW"
    , countryCode = Just 965
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryKY : PhoneNumbers.Territory
countryKY =
    { id = "KY"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryKZ : PhoneNumbers.Territory
countryKZ =
    { id = "KZ"
    , countryCode = Just 7
    , internationalPrefix = Just "810"
    , nationalPrefix = Just "8"
    }


{-| -}
countryLA : PhoneNumbers.Territory
countryLA =
    { id = "LA"
    , countryCode = Just 856
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryLB : PhoneNumbers.Territory
countryLB =
    { id = "LB"
    , countryCode = Just 961
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryLC : PhoneNumbers.Territory
countryLC =
    { id = "LC"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryLI : PhoneNumbers.Territory
countryLI =
    { id = "LI"
    , countryCode = Just 423
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryLK : PhoneNumbers.Territory
countryLK =
    { id = "LK"
    , countryCode = Just 94
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryLR : PhoneNumbers.Territory
countryLR =
    { id = "LR"
    , countryCode = Just 231
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryLS : PhoneNumbers.Territory
countryLS =
    { id = "LS"
    , countryCode = Just 266
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryLT : PhoneNumbers.Territory
countryLT =
    { id = "LT"
    , countryCode = Just 370
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "8"
    }


{-| -}
countryLU : PhoneNumbers.Territory
countryLU =
    { id = "LU"
    , countryCode = Just 352
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryLV : PhoneNumbers.Territory
countryLV =
    { id = "LV"
    , countryCode = Just 371
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryLY : PhoneNumbers.Territory
countryLY =
    { id = "LY"
    , countryCode = Just 218
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryMA : PhoneNumbers.Territory
countryMA =
    { id = "MA"
    , countryCode = Just 212
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryMC : PhoneNumbers.Territory
countryMC =
    { id = "MC"
    , countryCode = Just 377
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryMD : PhoneNumbers.Territory
countryMD =
    { id = "MD"
    , countryCode = Just 373
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryME : PhoneNumbers.Territory
countryME =
    { id = "ME"
    , countryCode = Just 382
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryMF : PhoneNumbers.Territory
countryMF =
    { id = "MF"
    , countryCode = Just 590
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryMG : PhoneNumbers.Territory
countryMG =
    { id = "MG"
    , countryCode = Just 261
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryMH : PhoneNumbers.Territory
countryMH =
    { id = "MH"
    , countryCode = Just 692
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryMK : PhoneNumbers.Territory
countryMK =
    { id = "MK"
    , countryCode = Just 389
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryML : PhoneNumbers.Territory
countryML =
    { id = "ML"
    , countryCode = Just 223
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryMM : PhoneNumbers.Territory
countryMM =
    { id = "MM"
    , countryCode = Just 95
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryMN : PhoneNumbers.Territory
countryMN =
    { id = "MN"
    , countryCode = Just 976
    , internationalPrefix = Just "001"
    , nationalPrefix = Just "0"
    }


{-| -}
countryMO : PhoneNumbers.Territory
countryMO =
    { id = "MO"
    , countryCode = Just 853
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryMP : PhoneNumbers.Territory
countryMP =
    { id = "MP"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryMQ : PhoneNumbers.Territory
countryMQ =
    { id = "MQ"
    , countryCode = Just 596
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryMR : PhoneNumbers.Territory
countryMR =
    { id = "MR"
    , countryCode = Just 222
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryMS : PhoneNumbers.Territory
countryMS =
    { id = "MS"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryMT : PhoneNumbers.Territory
countryMT =
    { id = "MT"
    , countryCode = Just 356
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryMU : PhoneNumbers.Territory
countryMU =
    { id = "MU"
    , countryCode = Just 230
    , internationalPrefix = Just "0(?:0|[24-7]0|3[03])"
    , nationalPrefix = Nothing
    }


{-| -}
countryMV : PhoneNumbers.Territory
countryMV =
    { id = "MV"
    , countryCode = Just 960
    , internationalPrefix = Just "0(?:0|19)"
    , nationalPrefix = Nothing
    }


{-| -}
countryMW : PhoneNumbers.Territory
countryMW =
    { id = "MW"
    , countryCode = Just 265
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryMX : PhoneNumbers.Territory
countryMX =
    { id = "MX"
    , countryCode = Just 52
    , internationalPrefix = Just "0[09]"
    , nationalPrefix = Just "01"
    }


{-| -}
countryMY : PhoneNumbers.Territory
countryMY =
    { id = "MY"
    , countryCode = Just 60
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryMZ : PhoneNumbers.Territory
countryMZ =
    { id = "MZ"
    , countryCode = Just 258
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryNA : PhoneNumbers.Territory
countryNA =
    { id = "NA"
    , countryCode = Just 264
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryNC : PhoneNumbers.Territory
countryNC =
    { id = "NC"
    , countryCode = Just 687
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryNE : PhoneNumbers.Territory
countryNE =
    { id = "NE"
    , countryCode = Just 227
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryNF : PhoneNumbers.Territory
countryNF =
    { id = "NF"
    , countryCode = Just 672
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryNG : PhoneNumbers.Territory
countryNG =
    { id = "NG"
    , countryCode = Just 234
    , internationalPrefix = Just "009"
    , nationalPrefix = Just "0"
    }


{-| -}
countryNI : PhoneNumbers.Territory
countryNI =
    { id = "NI"
    , countryCode = Just 505
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryNL : PhoneNumbers.Territory
countryNL =
    { id = "NL"
    , countryCode = Just 31
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryNO : PhoneNumbers.Territory
countryNO =
    { id = "NO"
    , countryCode = Just 47
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryNP : PhoneNumbers.Territory
countryNP =
    { id = "NP"
    , countryCode = Just 977
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryNR : PhoneNumbers.Territory
countryNR =
    { id = "NR"
    , countryCode = Just 674
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryNU : PhoneNumbers.Territory
countryNU =
    { id = "NU"
    , countryCode = Just 683
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryNZ : PhoneNumbers.Territory
countryNZ =
    { id = "NZ"
    , countryCode = Just 64
    , internationalPrefix = Just "0(?:0|161)"
    , nationalPrefix = Just "0"
    }


{-| -}
countryOM : PhoneNumbers.Territory
countryOM =
    { id = "OM"
    , countryCode = Just 968
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryPA : PhoneNumbers.Territory
countryPA =
    { id = "PA"
    , countryCode = Just 507
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryPE : PhoneNumbers.Territory
countryPE =
    { id = "PE"
    , countryCode = Just 51
    , internationalPrefix = Just "19(?:1[124]|77|90)00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryPF : PhoneNumbers.Territory
countryPF =
    { id = "PF"
    , countryCode = Just 689
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryPG : PhoneNumbers.Territory
countryPG =
    { id = "PG"
    , countryCode = Just 675
    , internationalPrefix = Just "00|140[1-3]"
    , nationalPrefix = Nothing
    }


{-| -}
countryPH : PhoneNumbers.Territory
countryPH =
    { id = "PH"
    , countryCode = Just 63
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryPK : PhoneNumbers.Territory
countryPK =
    { id = "PK"
    , countryCode = Just 92
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryPL : PhoneNumbers.Territory
countryPL =
    { id = "PL"
    , countryCode = Just 48
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryPM : PhoneNumbers.Territory
countryPM =
    { id = "PM"
    , countryCode = Just 508
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryPR : PhoneNumbers.Territory
countryPR =
    { id = "PR"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryPS : PhoneNumbers.Territory
countryPS =
    { id = "PS"
    , countryCode = Just 970
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryPT : PhoneNumbers.Territory
countryPT =
    { id = "PT"
    , countryCode = Just 351
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryPW : PhoneNumbers.Territory
countryPW =
    { id = "PW"
    , countryCode = Just 680
    , internationalPrefix = Just "01[12]"
    , nationalPrefix = Nothing
    }


{-| -}
countryPY : PhoneNumbers.Territory
countryPY =
    { id = "PY"
    , countryCode = Just 595
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryQA : PhoneNumbers.Territory
countryQA =
    { id = "QA"
    , countryCode = Just 974
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryRE : PhoneNumbers.Territory
countryRE =
    { id = "RE"
    , countryCode = Just 262
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryRO : PhoneNumbers.Territory
countryRO =
    { id = "RO"
    , countryCode = Just 40
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryRS : PhoneNumbers.Territory
countryRS =
    { id = "RS"
    , countryCode = Just 381
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryRU : PhoneNumbers.Territory
countryRU =
    { id = "RU"
    , countryCode = Just 7
    , internationalPrefix = Just "810"
    , nationalPrefix = Just "8"
    }


{-| -}
countryRW : PhoneNumbers.Territory
countryRW =
    { id = "RW"
    , countryCode = Just 250
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countrySA : PhoneNumbers.Territory
countrySA =
    { id = "SA"
    , countryCode = Just 966
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countrySB : PhoneNumbers.Territory
countrySB =
    { id = "SB"
    , countryCode = Just 677
    , internationalPrefix = Just "0[01]"
    , nationalPrefix = Nothing
    }


{-| -}
countrySC : PhoneNumbers.Territory
countrySC =
    { id = "SC"
    , countryCode = Just 248
    , internationalPrefix = Just "0(?:[02]|10?)"
    , nationalPrefix = Nothing
    }


{-| -}
countrySD : PhoneNumbers.Territory
countrySD =
    { id = "SD"
    , countryCode = Just 249
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countrySE : PhoneNumbers.Territory
countrySE =
    { id = "SE"
    , countryCode = Just 46
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countrySG : PhoneNumbers.Territory
countrySG =
    { id = "SG"
    , countryCode = Just 65
    , internationalPrefix = Just "0[0-3]\\d"
    , nationalPrefix = Nothing
    }


{-| -}
countrySH : PhoneNumbers.Territory
countrySH =
    { id = "SH"
    , countryCode = Just 290
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countrySI : PhoneNumbers.Territory
countrySI =
    { id = "SI"
    , countryCode = Just 386
    , internationalPrefix = Just "00|10(?:22|66|88|99)"
    , nationalPrefix = Just "0"
    }


{-| -}
countrySJ : PhoneNumbers.Territory
countrySJ =
    { id = "SJ"
    , countryCode = Just 47
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countrySK : PhoneNumbers.Territory
countrySK =
    { id = "SK"
    , countryCode = Just 421
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countrySL : PhoneNumbers.Territory
countrySL =
    { id = "SL"
    , countryCode = Just 232
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countrySM : PhoneNumbers.Territory
countrySM =
    { id = "SM"
    , countryCode = Just 378
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countrySN : PhoneNumbers.Territory
countrySN =
    { id = "SN"
    , countryCode = Just 221
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countrySO : PhoneNumbers.Territory
countrySO =
    { id = "SO"
    , countryCode = Just 252
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countrySR : PhoneNumbers.Territory
countrySR =
    { id = "SR"
    , countryCode = Just 597
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countrySS : PhoneNumbers.Territory
countrySS =
    { id = "SS"
    , countryCode = Just 211
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryST : PhoneNumbers.Territory
countryST =
    { id = "ST"
    , countryCode = Just 239
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countrySV : PhoneNumbers.Territory
countrySV =
    { id = "SV"
    , countryCode = Just 503
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countrySX : PhoneNumbers.Territory
countrySX =
    { id = "SX"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countrySY : PhoneNumbers.Territory
countrySY =
    { id = "SY"
    , countryCode = Just 963
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countrySZ : PhoneNumbers.Territory
countrySZ =
    { id = "SZ"
    , countryCode = Just 268
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryTA : PhoneNumbers.Territory
countryTA =
    { id = "TA"
    , countryCode = Just 290
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryTC : PhoneNumbers.Territory
countryTC =
    { id = "TC"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryTD : PhoneNumbers.Territory
countryTD =
    { id = "TD"
    , countryCode = Just 235
    , internationalPrefix = Just "00|16"
    , nationalPrefix = Nothing
    }


{-| -}
countryTG : PhoneNumbers.Territory
countryTG =
    { id = "TG"
    , countryCode = Just 228
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryTH : PhoneNumbers.Territory
countryTH =
    { id = "TH"
    , countryCode = Just 66
    , internationalPrefix = Just "00[1-9]"
    , nationalPrefix = Just "0"
    }


{-| -}
countryTJ : PhoneNumbers.Territory
countryTJ =
    { id = "TJ"
    , countryCode = Just 992
    , internationalPrefix = Just "810"
    , nationalPrefix = Just "8"
    }


{-| -}
countryTK : PhoneNumbers.Territory
countryTK =
    { id = "TK"
    , countryCode = Just 690
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryTL : PhoneNumbers.Territory
countryTL =
    { id = "TL"
    , countryCode = Just 670
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryTM : PhoneNumbers.Territory
countryTM =
    { id = "TM"
    , countryCode = Just 993
    , internationalPrefix = Just "810"
    , nationalPrefix = Just "8"
    }


{-| -}
countryTN : PhoneNumbers.Territory
countryTN =
    { id = "TN"
    , countryCode = Just 216
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryTO : PhoneNumbers.Territory
countryTO =
    { id = "TO"
    , countryCode = Just 676
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryTR : PhoneNumbers.Territory
countryTR =
    { id = "TR"
    , countryCode = Just 90
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryTT : PhoneNumbers.Territory
countryTT =
    { id = "TT"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryTV : PhoneNumbers.Territory
countryTV =
    { id = "TV"
    , countryCode = Just 688
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryTW : PhoneNumbers.Territory
countryTW =
    { id = "TW"
    , countryCode = Just 886
    , internationalPrefix = Just "0(?:0[25-79]|19)"
    , nationalPrefix = Just "0"
    }


{-| -}
countryTZ : PhoneNumbers.Territory
countryTZ =
    { id = "TZ"
    , countryCode = Just 255
    , internationalPrefix = Just "00[056]"
    , nationalPrefix = Just "0"
    }


{-| -}
countryUA : PhoneNumbers.Territory
countryUA =
    { id = "UA"
    , countryCode = Just 380
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryUG : PhoneNumbers.Territory
countryUG =
    { id = "UG"
    , countryCode = Just 256
    , internationalPrefix = Just "00[057]"
    , nationalPrefix = Just "0"
    }


{-| -}
countryUS : PhoneNumbers.Territory
countryUS =
    { id = "US"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryUY : PhoneNumbers.Territory
countryUY =
    { id = "UY"
    , countryCode = Just 598
    , internationalPrefix = Just "0(?:0|1[3-9]\\d)"
    , nationalPrefix = Just "0"
    }


{-| -}
countryUZ : PhoneNumbers.Territory
countryUZ =
    { id = "UZ"
    , countryCode = Just 998
    , internationalPrefix = Just "810"
    , nationalPrefix = Just "8"
    }


{-| -}
countryVA : PhoneNumbers.Territory
countryVA =
    { id = "VA"
    , countryCode = Just 39
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryVC : PhoneNumbers.Territory
countryVC =
    { id = "VC"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryVE : PhoneNumbers.Territory
countryVE =
    { id = "VE"
    , countryCode = Just 58
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryVG : PhoneNumbers.Territory
countryVG =
    { id = "VG"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryVI : PhoneNumbers.Territory
countryVI =
    { id = "VI"
    , countryCode = Just 1
    , internationalPrefix = Just "011"
    , nationalPrefix = Just "1"
    }


{-| -}
countryVN : PhoneNumbers.Territory
countryVN =
    { id = "VN"
    , countryCode = Just 84
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryVU : PhoneNumbers.Territory
countryVU =
    { id = "VU"
    , countryCode = Just 678
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryWF : PhoneNumbers.Territory
countryWF =
    { id = "WF"
    , countryCode = Just 681
    , internationalPrefix = Just "00"
    , nationalPrefix = Nothing
    }


{-| -}
countryWS : PhoneNumbers.Territory
countryWS =
    { id = "WS"
    , countryCode = Just 685
    , internationalPrefix = Just "0"
    , nationalPrefix = Nothing
    }


{-| -}
countryXK : PhoneNumbers.Territory
countryXK =
    { id = "XK"
    , countryCode = Just 383
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryYE : PhoneNumbers.Territory
countryYE =
    { id = "YE"
    , countryCode = Just 967
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryYT : PhoneNumbers.Territory
countryYT =
    { id = "YT"
    , countryCode = Just 262
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryZA : PhoneNumbers.Territory
countryZA =
    { id = "ZA"
    , countryCode = Just 27
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryZM : PhoneNumbers.Territory
countryZM =
    { id = "ZM"
    , countryCode = Just 260
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }


{-| -}
countryZW : PhoneNumbers.Territory
countryZW =
    { id = "ZW"
    , countryCode = Just 263
    , internationalPrefix = Just "00"
    , nationalPrefix = Just "0"
    }
