const xml2js = require ('xml2js');
const fs = require('fs');

const dbString = fs.readFileSync('phone_db.xml', 'utf-8');
const targetPath = 'src/PhoneNumbers/Countries.elm';

const header = `
module PhoneNumbers.Countries exposing (..)

{-| This file is auto generated. Do not edit this file directly.
-}

import PhoneNumbers
`;

const parseOptions = {
  trim: true,
  explicitRoot: false
};

xml2js.parseString(dbString, parseOptions, (err, result) => {
  if (err) {
    console.log(err);
    return;
  }

  const converted = result.territories[0].territory
        .filter(filterTerritory)
        .map(territoryToJSON)
        .map(elmify)
        .join('');

  const countryFileContent = header + converted;
  fs.writeFileSync(targetPath, countryFileContent, 'utf-8');
});

function filterTerritory(territory) {
  return isNaN(territory.$.id);
}

function territoryToJSON(territory) {
  const numberDescriptions = [];

  for (const key in territory) {
    const keyType = numberDescriptionKeyType(key);
    if (keyType) {
      const numberDescription = numberDescriptionToJSON(keyType, territory[key][0]);
      numberDescriptions.push(numberDescription);
    }
  }

  return {
    id: territory.$.id,
    countryCode: territory.$.countryCode,
    internationalPrefix: territory.$.internationalPrefix,
    nationalPrefix: territory.$.nationalPrefix,
    numberDescriptions: numberDescriptions
  };
}

function numberDescriptionToJSON(keyType, data) {
  return {
    descriptionType: keyType,
    exampleNumber: extractXmlSingleValue(data.exampleNumber),
    possibleLengths: data.possibleLengths,
    pattern: extractXmlSingleValue(data.nationalNumberPattern)
  };
}

function extractXmlSingleValue(xml) {
  if (!xml) {
    return undefined;
  }

  if (xml.length !== 1) {
    throw `Xml value does not match spec: ${xml}`;
  }

  return xml[0];
}

function numberDescriptionKeyType(key) {
  const numberDescriptions = {
    generalDesc: 'GeneralDesc',
    fixedLine: 'FixedLine',
    mobile: 'Mobile',
    tollFree: 'TollFree',
    premiumRate: 'PremiumRate',
    sharedCost: 'SharedCost',
    personalNumber: 'PersonalNumber',
    voip: 'Voip',
    pager: 'Pager',
    uan: 'Uan',
    emergency: 'Emergency',
    voicemail: 'Voicemail',
    shortCode: 'ShortCode',
    standardRate: 'StandardRate',
    carrierSpecific: 'CarrierSpecific',
    smsService: 'SmsService',
    noInternationalDialling: 'NoInternationalDialling',
  };

  return numberDescriptions[key];
}

function elmify(territory) {
  const numberDescriptions = territory.numberDescriptions.map(elmifyNumberDescription);

  return `
{-|-}
country${territory.id} : PhoneNumbers.Territory
country${territory.id} =
    { id = "${territory.id}"
    , countryCode = ${elmMaybe(territory.countryCode, false)}
    , internationalPrefix = ${elmMaybe(territory.internationalPrefix, true)}
    , nationalPrefix = ${elmMaybe(territory.nationalPrefix, true)}
    , numberDescriptions = ${elmList(numberDescriptions)}
    }
`;
}

function elmifyNumberDescription(data) {
  return `{
    descriptionType = ${data.descriptionType}
    , exampleNumber = "${data.exampleNumber || ''}"
    , pattern = "${elmCleanString(data.pattern)}"
}`;
}

function elmMaybe(maybeVal, isString) {
  if (maybeVal) {
    if (isString) {
      return `Just "${elmCleanString(maybeVal)}"`;
    }

    return `Just ${maybeVal}`;
  }

  return 'Nothing';
}

function elmCleanString(str) {
  return str.replace(/\\/g, '\\\\').replace(/\s/g, '');
}

function elmList(arr) {
  return `[${arr.join(', ')}]`;
}
