const xml2js = require ('xml2js');
const fs = require('fs');

const dbString = fs.readFileSync('phone_db.xml', 'utf-8');
const targetPath = 'src/PhoneNumbers/Countries.elm';

const header = `
module PhoneNumbers.Countries exposing (..)

{-| This file is auto generated. Do not edit this file directly.
-}

import Regex
import PhoneNumbers exposing (Territory, DescriptionType(..))
`;

const parseOptions = {
  trim: true,
  explicitRoot: false
};

xml2js.parseString(dbString, parseOptions, (err, result) => {
  if (err) {
    console.log(err);
    return;
  }

  const territories = result.territories[0].territory
        .filter(filterTerritory)
        .map(territoryToJSON);

  const elmAllTerritories = `
{-| -}
all : List Territory
all = ${elmList(territories.map(t => "country" + t.id))}
`;

  const elmTerritories = territories
        .map(elmify)
        .join('');

  const countryFileContent = header + elmAllTerritories + elmTerritories;
  fs.writeFileSync(targetPath, countryFileContent, 'utf-8');
});

function filterTerritory(territory) {
  return isNaN(territory.$.id);
}

function territoryToJSON(territory) {
  const numberDescriptions = [];

  for (const key in territory) {
    const keyType = numberDescriptionKeyType(key);
    if (keyType) {
      const numberDescription = numberDescriptionToJSON(keyType, territory[key][0]);
      numberDescriptions.push(numberDescription);
    }
  }

  let availableFormats = [];
  if (territory.availableFormats) {
    const data = extractXmlSingleValue(territory.availableFormats);
    availableFormats = data.numberFormat.map(availableFormatToJSON);
  }

  return {
    id: territory.$.id,
    countryCode: territory.$.countryCode,
    internationalPrefix: territory.$.internationalPrefix,
    nationalPrefix: territory.$.nationalPrefix,
    availableFormats: availableFormats,
    numberDescriptions: numberDescriptions
  };
}

function availableFormatToJSON(data) {
  return {
    pattern: data.$.pattern,
    format: extractXmlSingleValue(data.format),
    leadingDigits: data.leadingDigits
  };
}

function numberDescriptionToJSON(keyType, data) {
  return {
    descriptionType: keyType,
    exampleNumber: extractXmlSingleValue(data.exampleNumber),
    possibleLengths: extractXmlSingleValue(data.possibleLengths),
    pattern: extractXmlSingleValue(data.nationalNumberPattern)
  };
}

function extractXmlSingleValue(xml) {
  if (!xml) {
    return undefined;
  }

  if (xml.length !== 1) {
    throw `Xml value does not match spec: ${xml}`;
  }

  return xml[0];
}

function numberDescriptionKeyType(key) {
  const numberDescriptions = {
    generalDesc: 'GeneralDesc',
    fixedLine: 'FixedLine',
    mobile: 'Mobile',
    tollFree: 'TollFree',
    premiumRate: 'PremiumRate',
    sharedCost: 'SharedCost',
    personalNumber: 'PersonalNumber',
    voip: 'Voip',
    pager: 'Pager',
    uan: 'Uan',
    emergency: 'Emergency',
    voicemail: 'Voicemail',
    shortCode: 'ShortCode',
    standardRate: 'StandardRate',
    carrierSpecific: 'CarrierSpecific',
    smsService: 'SmsService',
    noInternationalDialling: 'NoInternationalDialling',
  };

  return numberDescriptions[key];
}

function elmify(territory) {
  const availableFormats = territory.availableFormats.map(elmifyAvailableFormats);
  const numberDescriptions = territory.numberDescriptions.map(elmifyNumberDescription);

  return `
{-|-}
country${territory.id} : Territory
country${territory.id} =
    { id = "${territory.id}"
    , countryCode = ${elmMaybe(territory.countryCode, false)}
    , internationalPrefix = ${elmMaybe(territory.internationalPrefix, true)}
    , nationalPrefix = ${elmMaybe(territory.nationalPrefix, true)}
    , availableFormats = ${elmList(availableFormats)}
    , numberDescriptions = ${elmList(numberDescriptions)}
    }
`;
}

function elmifyAvailableFormats(data) {
  return `{
   pattern = ${elmRegex(data.pattern)}
   , format = "${data.format}"
   , leadingDigits = ${elmList((data.leadingDigits || []).map(elmRegex))}
}`;
}

function elmifyNumberDescription(data) {
  return `{
    descriptionType = ${data.descriptionType}
    , exampleNumber = "${data.exampleNumber || ''}"
    , possibleLengths = ${elmifyPossibleLengths(data.possibleLengths)}
    , pattern = ${elmRegex(data.pattern)}
}`;
}

function elmifyPossibleLengths(maybeData) {
  return elmMaybe2(maybeData, (data) => `{
national = ${elmRegex(data.$.national)}
, localOnly = ${elmMaybe2(data.$.localOnly, (l) => elmRegex(l))}
}
`);
}

function elmMaybe(maybeVal, isString) {
  if (isString) {
    return elmMaybe2(maybeVal, (v) => `"${elmCleanString(maybeVal)}"`);
  }

  return elmMaybe2(maybeVal, (v) => v);
}

function elmMaybe2(maybeVal, onValue) {
  if (maybeVal) {
    return `Just ${onValue(maybeVal)}`;
  }

  return 'Nothing';
}

function elmCleanString(str) {
  return str.replace(/\\/g, '\\\\').replace(/\s/g, '');
}

function elmList(arr) {
  return `[${arr.join(',\n')}]`;
}

function elmRegex(str) {
  return `("${elmCleanString(str)}"
|>Regex.fromString
|>Maybe.withDefault Regex.never
)`;
}
